/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.onlinerpg;

import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.UIManager;

/**
 *
 * @author vadimkaz58
 */
public class Game extends javax.swing.JPanel {
    
    boolean online;
    String name;
    Main main;
    /**
     * Creates new form Game
     */
    public Game(Main main, String name, boolean online) {
        this.online = online;
        this.name = name;
        this.main = main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        UIManager.getDefaults().put("TabbedPane.contentBorderInsets", new Insets(0,0,0,0)); UIManager.getDefaults().put("TabbedPane.tabsOverlapBorder", true); jTabbedPane1.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() { private final java.awt.Insets borderInsets = new java.awt.Insets(0,0,0,0); @Override protected void paintContentBorder(Graphics g, int tabPlacement, int selectedIndex) { } @Override protected Insets getContentBorderInsets(int tabPlacement) {     return borderInsets; } });
        jTabbedPane1.setUI(new javax.swing.plaf.metal.MetalTabbedPaneUI(){
            protected void paintTabArea(Graphics g,int tabPlacement,int selectedIndex){} });
    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();

    setBackground(new java.awt.Color(255, 204, 204));
    setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

    jTabbedPane1.setBackground(new java.awt.Color(255, 204, 204));
    jTabbedPane1.setMinimumSize(new java.awt.Dimension(500, 500));
    jTabbedPane1.setPreferredSize(new java.awt.Dimension(500, 500));

    jPanel1.setBackground(new java.awt.Color(255, 204, 204));
    java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
    jPanel1Layout.columnWidths = new int[] {0, 13, 0, 13, 0, 13, 0};
    jPanel1Layout.rowHeights = new int[] {0, 13, 0, 13, 0};
    jPanel1.setLayout(jPanel1Layout);

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Имя", "Очки"
        }
    ));
    jScrollPane1.setViewportView(jTable1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.ipadx = 250;
    gridBagConstraints.ipady = 250;
    jPanel1.add(jScrollPane1, gridBagConstraints);

    jButton1.setText("Отмена");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    jPanel1.add(jButton1, gridBagConstraints);

    jButton2.setText("Принять");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
    jPanel1.add(jButton2, gridBagConstraints);

    jLabel1.setBackground(new java.awt.Color(0, 0, 0));
    jLabel1.setForeground(new java.awt.Color(0, 0, 0));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 7;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    jPanel1.add(jLabel1, gridBagConstraints);

    jTabbedPane1.addTab("tab1", jPanel1);

    jPanel2.setBackground(new java.awt.Color(255, 204, 204));

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 500, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 467, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("tab2", jPanel2);

    add(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        main.openMenu(menu);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
