/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.onlinerpg;

import java.awt.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.*;
import java.util.Formatter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author vadimkaz58
 */
public class Menu extends javax.swing.JFrame {
    
    public Dimension dimension;
    public GraphicsDevice gfxDev;
    public GraphicsEnvironment gfxEnv;
    public String[][] servers;
    public ArrayList<String> serversName;
    public ArrayList<String> serversIp;
    public ArrayList<String> serversPass;
    public boolean online = false;
    public int accountPage = 9;
    public String name;
    private String ipBDServer;
    /**
     * Creates new form Menu
     */
    
    public Menu() {
        dimension = new Dimension();
        gfxEnv = GraphicsEnvironment.getLocalGraphicsEnvironment();
        gfxDev = gfxEnv.getDefaultScreenDevice();
        initComponents();
        serversName = new ArrayList();
        serversIp = new ArrayList();
        serversPass = new ArrayList();   
        try{
            Scanner scanner = new Scanner(new File("config.ini"));
            scanner.next();
            if (scanner.next().equals("true")) {
                gfxDev.setFullScreenWindow(this);
                jComboBox1.setEnabled(false);
                jToggleButton1.setSelected(true);
                scanner.next();
                dimension.width = Integer.parseInt(scanner.next());
                dimension.height = Integer.parseInt(scanner.next());
            } else {
                scanner.next();
                dimension.width = Integer.parseInt(scanner.next());
                dimension.height = Integer.parseInt(scanner.next());
                this.setSize(dimension);
            }
            jComboBox1.setSelectedIndex(Integer.parseInt(scanner.next()));
            scanner.close();
        }catch (Exception e) {
            System.out.println(e);
        }
        try {
            Scanner scanner = new Scanner(new File("servers.txt"));
            while (scanner.hasNext()) {
                serversName.add(scanner.next());
                serversIp.add(scanner.next());
                serversPass.add(scanner.next());
            }
            scanner.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        for (int i = 0; i < serversName.size(); i++) {
            listModel.addElement(serversName.get(i));
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        UIManager.getDefaults().put("TabbedPane.contentBorderInsets", new Insets(0,0,0,0)); UIManager.getDefaults().put("TabbedPane.tabsOverlapBorder", true); jTabbedPane1.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() { private final java.awt.Insets borderInsets = new java.awt.Insets(0,0,0,0); @Override protected void paintContentBorder(Graphics g, int tabPlacement, int selectedIndex) { } @Override protected Insets getContentBorderInsets(int tabPlacement) {     return borderInsets; } });
        jTabbedPane1.setUI(new javax.swing.plaf.metal.MetalTabbedPaneUI(){
            protected void paintTabArea(Graphics g,int tabPlacement,int selectedIndex){} });
    jPanel2 = new javax.swing.JPanel();
    jButton3 = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jLabel11 = new javax.swing.JLabel();
    jPanel5 = new javax.swing.JPanel();
    accept = new javax.swing.JButton();
    jToggleButton1 = new javax.swing.JToggleButton();
    cancel = new javax.swing.JButton();
    jComboBox1 = new javax.swing.JComboBox<>();
    jButton11 = new javax.swing.JButton();
    jCheckBox3 = new javax.swing.JCheckBox();
    jPanel6 = new javax.swing.JPanel();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jPanel7 = new javax.swing.JPanel();
    jButton7 = new javax.swing.JButton();
    jCheckBox1 = new javax.swing.JCheckBox();
    jButton8 = new javax.swing.JButton();
    jTextField1 = new javax.swing.JTextField();
    jTextField2 = new javax.swing.JTextField();
    jCheckBox2 = new javax.swing.JCheckBox();
    jLabel1 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList<>();
    jButton10 = new javax.swing.JButton();
    jButton9 = new javax.swing.JButton();
    jButton17 = new javax.swing.JButton();
    jButton18 = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    jTextField4 = new javax.swing.JTextField();
    jTextField5 = new javax.swing.JTextField();
    jButton12 = new javax.swing.JButton();
    jButton13 = new javax.swing.JButton();
    jButton14 = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jPanel8 = new javax.swing.JPanel();
    jTextField6 = new javax.swing.JTextField();
    jPasswordField1 = new javax.swing.JPasswordField();
    jPasswordField2 = new javax.swing.JPasswordField();
    jButton15 = new javax.swing.JButton();
    jButton16 = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jPanel9 = new javax.swing.JPanel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jButton19 = new javax.swing.JButton();
    jButton20 = new javax.swing.JButton();
    jTextField3 = new javax.swing.JTextField();
    jPasswordField3 = new javax.swing.JPasswordField();
    jLabel9 = new javax.swing.JLabel();
    jTextField7 = new javax.swing.JTextField();
    jPanel10 = new javax.swing.JPanel();
    jButton21 = new javax.swing.JButton();
    jPanel11 = new javax.swing.JPanel();
    jTextField8 = new javax.swing.JTextField();
    jButton22 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(255, 204, 204));
    jPanel1.setForeground(new java.awt.Color(255, 204, 204));
    jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
    jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

    jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));
    jTabbedPane1.setForeground(new java.awt.Color(255, 204, 204));

    jPanel2.setBackground(new java.awt.Color(255, 204, 204));
    jPanel2.setForeground(new java.awt.Color(255, 204, 204));
    java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
    jPanel2Layout.columnWidths = new int[] {0, 5, 0};
    jPanel2Layout.rowHeights = new int[] {0, 32, 0, 32, 0, 32, 0};
    jPanel2.setLayout(jPanel2Layout);

    jButton3.setBackground(new java.awt.Color(102, 102, 102));
    jButton3.setText("Выйти");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    jPanel2.add(jButton3, gridBagConstraints);

    jButton1.setBackground(new java.awt.Color(102, 102, 102));
    jButton1.setText("Начать игру");
    jButton1.setEnabled(false);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    jPanel2.add(jButton1, gridBagConstraints);

    jButton2.setBackground(new java.awt.Color(102, 102, 102));
    jButton2.setText("Настройки");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    jPanel2.add(jButton2, gridBagConstraints);

    jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(0, 0, 102));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    jPanel2.add(jLabel11, gridBagConstraints);
    jLabel11.getAccessibleContext().setAccessibleName("jname");

    jTabbedPane1.addTab("Main", jPanel2);

    jPanel5.setBackground(new java.awt.Color(255, 204, 204));
    jPanel5.setForeground(new java.awt.Color(255, 204, 204));
    java.awt.GridBagLayout jPanel5Layout = new java.awt.GridBagLayout();
    jPanel5Layout.columnWidths = new int[] {0, 5, 0, 5, 0};
    jPanel5Layout.rowHeights = new int[] {0, 32, 0, 32, 0, 32, 0};
    jPanel5.setLayout(jPanel5Layout);

    accept.setText("Принять");
    accept.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            acceptActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 6;
    jPanel5.add(accept, gridBagConstraints);

    jToggleButton1.setText("Полный экран");
    jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton1ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    jPanel5.add(jToggleButton1, gridBagConstraints);

    cancel.setText("Отмена");
    cancel.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    jPanel5.add(cancel, gridBagConstraints);
    cancel.getAccessibleContext().setAccessibleName("jButton5");

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "500x500", "640x480", "1024x768", "1280x720", "1280x1024" }));
    jComboBox1.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jComboBox1ItemStateChanged(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel5.add(jComboBox1, gridBagConstraints);

    jButton11.setText("Учётная запись");
    jButton11.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton11ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel5.add(jButton11, gridBagConstraints);

    jCheckBox3.setForeground(new java.awt.Color(0, 0, 0));
    jCheckBox3.setSelected(true);
    jCheckBox3.setText("Онлайн");
    jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jCheckBox3ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 4;
    jPanel5.add(jCheckBox3, gridBagConstraints);

    jTabbedPane1.addTab("Option", jPanel5);

    jPanel6.setBackground(new java.awt.Color(255, 204, 204));
    jPanel6.setForeground(new java.awt.Color(255, 204, 204));
    java.awt.GridBagLayout jPanel6Layout = new java.awt.GridBagLayout();
    jPanel6Layout.columnWidths = new int[] {0};
    jPanel6Layout.rowHeights = new int[] {0, 32, 0, 32, 0};
    jPanel6.setLayout(jPanel6Layout);

    jButton4.setText("Создать игру");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    jPanel6.add(jButton4, gridBagConstraints);

    jButton5.setText("Присоединиться");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    jPanel6.add(jButton5, gridBagConstraints);

    jButton6.setText("Отмена");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    jPanel6.add(jButton6, gridBagConstraints);

    jTabbedPane1.addTab("Start Game", jPanel6);

    jPanel7.setBackground(new java.awt.Color(255, 204, 204));
    jPanel7.setForeground(new java.awt.Color(255, 204, 204));
    java.awt.GridBagLayout jPanel7Layout = new java.awt.GridBagLayout();
    jPanel7Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
    jPanel7Layout.rowHeights = new int[] {0, 32, 0, 32, 0, 32, 0};
    jPanel7.setLayout(jPanel7Layout);

    jButton7.setText("Отмена");
    jButton7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton7ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    jPanel7.add(jButton7, gridBagConstraints);

    jCheckBox1.setForeground(new java.awt.Color(102, 102, 102));
    jCheckBox1.setText("Пароль");
    jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jCheckBox1ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 2;
    jPanel7.add(jCheckBox1, gridBagConstraints);

    jButton8.setText("Принять");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 6;
    jPanel7.add(jButton8, gridBagConstraints);

    jTextField1.setText("New world");
    jTextField1.setToolTipText("");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel7.add(jTextField1, gridBagConstraints);
    jTextField1.getAccessibleContext().setAccessibleName("");

    jTextField2.setEnabled(false);
    jTextField2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField2ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel7.add(jTextField2, gridBagConstraints);

    jCheckBox2.setForeground(new java.awt.Color(102, 102, 102));
    jCheckBox2.setText("Одиночная игра");
    jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jCheckBox2ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    jPanel7.add(jCheckBox2, gridBagConstraints);

    jLabel1.setForeground(new java.awt.Color(102, 102, 102));
    jLabel1.setText("Название сервера");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 0;
    jPanel7.add(jLabel1, gridBagConstraints);

    jTabbedPane1.addTab("Create game", jPanel7);

    jPanel3.setBackground(new java.awt.Color(255, 204, 204));
    jPanel3.setMinimumSize(new java.awt.Dimension(500, 500));
    jPanel3.setPreferredSize(new java.awt.Dimension(500, 500));
    java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
    jPanel3Layout.columnWidths = new int[] {0, 5, 0, 5, 0};
    jPanel3Layout.rowHeights = new int[] {0, 32, 0, 32, 0};
    jPanel3.setLayout(jPanel3Layout);

    listModel = new DefaultListModel();
    jList1.setBackground(new java.awt.Color(255, 255, 255));
    jList1.setForeground(new java.awt.Color(0, 0, 0));
    jList1.setModel(listModel);
    jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jList1.setToolTipText("");
    jScrollPane1.setViewportView(jList1);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    jPanel3.add(jScrollPane1, gridBagConstraints);

    jButton10.setText("Принять");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    jPanel3.add(jButton10, gridBagConstraints);

    jButton9.setText("Отмена");
    jButton9.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton9ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.ipadx = 36;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    jPanel3.add(jButton9, gridBagConstraints);

    jButton17.setText("Удалить");
    jButton17.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton17ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    jPanel3.add(jButton17, gridBagConstraints);

    jButton18.setText("Добавить");
    jButton18.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton18ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    jPanel3.add(jButton18, gridBagConstraints);

    jTabbedPane1.addTab("Connect", jPanel3);

    jPanel4.setBackground(new java.awt.Color(255, 204, 204));
    java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
    jPanel4Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
    jPanel4Layout.rowHeights = new int[] {0, 32, 0, 32, 0, 32, 0};
    jPanel4.setLayout(jPanel4Layout);

    jTextField4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField4ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel4.add(jTextField4, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel4.add(jTextField5, gridBagConstraints);

    jButton12.setText("Отмена");
    jButton12.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton12ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    jPanel4.add(jButton12, gridBagConstraints);

    jButton13.setText("Принять");
    jButton13.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton13ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 6;
    jPanel4.add(jButton13, gridBagConstraints);

    jButton14.setText("Зарегистрироваться");
    jButton14.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton14ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 6;
    jPanel4.add(jButton14, gridBagConstraints);

    jLabel2.setForeground(new java.awt.Color(0, 0, 0));
    jLabel2.setText("Логин:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    jPanel4.add(jLabel2, gridBagConstraints);

    jLabel3.setForeground(new java.awt.Color(0, 0, 0));
    jLabel3.setText("Пароль:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    jPanel4.add(jLabel3, gridBagConstraints);

    jLabel10.setForeground(new java.awt.Color(204, 51, 0));
    jLabel10.setText("Неверный логин или пароль!");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel4.add(jLabel10, gridBagConstraints);
    jLabel10.setVisible(false);

    jTabbedPane1.addTab("log", jPanel4);

    jPanel8.setBackground(new java.awt.Color(255, 204, 204));
    java.awt.GridBagLayout jPanel8Layout = new java.awt.GridBagLayout();
    jPanel8Layout.columnWidths = new int[] {0, 5, 0, 5, 0};
    jPanel8Layout.rowHeights = new int[] {0, 32, 0, 32, 0, 32, 0};
    jPanel8.setLayout(jPanel8Layout);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel8.add(jTextField6, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel8.add(jPasswordField1, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel8.add(jPasswordField2, gridBagConstraints);

    jButton15.setText("Отмена");
    jButton15.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton15ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    jPanel8.add(jButton15, gridBagConstraints);

    jButton16.setText("Принять");
    jButton16.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton16ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 6;
    jPanel8.add(jButton16, gridBagConstraints);

    jLabel4.setForeground(new java.awt.Color(0, 0, 0));
    jLabel4.setText("Логин");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    jPanel8.add(jLabel4, gridBagConstraints);

    jLabel5.setForeground(new java.awt.Color(0, 0, 0));
    jLabel5.setText("Пароль");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    jPanel8.add(jLabel5, gridBagConstraints);

    jLabel6.setForeground(new java.awt.Color(0, 0, 0));
    jLabel6.setText("Повтор пароля");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    jPanel8.add(jLabel6, gridBagConstraints);

    jTabbedPane1.addTab("sign", jPanel8);

    jPanel9.setBackground(new java.awt.Color(255, 204, 204));
    java.awt.GridBagLayout jPanel9Layout = new java.awt.GridBagLayout();
    jPanel9Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
    jPanel9Layout.rowHeights = new int[] {0, 32, 0, 32, 0, 32, 0, 32, 0};
    jPanel9.setLayout(jPanel9Layout);

    jLabel7.setForeground(new java.awt.Color(0, 0, 0));
    jLabel7.setText("Название");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    jPanel9.add(jLabel7, gridBagConstraints);

    jLabel8.setForeground(new java.awt.Color(0, 0, 0));
    jLabel8.setText("ip:port");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 0;
    jPanel9.add(jLabel8, gridBagConstraints);

    jButton19.setText("Отмена");
    jButton19.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton19ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 8;
    jPanel9.add(jButton19, gridBagConstraints);

    jButton20.setText("Добавить");
    jButton20.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton20ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 6;
    gridBagConstraints.gridy = 8;
    jPanel9.add(jButton20, gridBagConstraints);

    jTextField3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField3ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel9.add(jTextField3, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel9.add(jPasswordField3, gridBagConstraints);

    jLabel9.setForeground(new java.awt.Color(0, 0, 0));
    jLabel9.setText("Пароль");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 6;
    jPanel9.add(jLabel9, gridBagConstraints);

    jTextField7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField7ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel9.add(jTextField7, gridBagConstraints);

    jTabbedPane1.addTab("Add connect", jPanel9);

    jPanel10.setBackground(new java.awt.Color(255, 204, 204));
    java.awt.GridBagLayout jPanel10Layout = new java.awt.GridBagLayout();
    jPanel10Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
    jPanel10Layout.rowHeights = new int[] {0, 0, 0, 0, 0};
    jPanel10.setLayout(jPanel10Layout);

    jButton21.setText("Выход");
    jButton21.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton21ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 7;
    gridBagConstraints.gridheight = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    jPanel10.add(jButton21, gridBagConstraints);

    jTabbedPane1.addTab("Log out", jPanel10);

    jPanel11.setBackground(new java.awt.Color(255, 204, 204));
    java.awt.GridBagLayout jPanel11Layout = new java.awt.GridBagLayout();
    jPanel11Layout.columnWidths = new int[] {0, 40, 0, 40, 0};
    jPanel11Layout.rowHeights = new int[] {0, 32, 0};
    jPanel11.setLayout(jPanel11Layout);

    jTextField8.setToolTipText("ipserver");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    jPanel11.add(jTextField8, gridBagConstraints);

    jButton22.setText("Принять");
    jButton22.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton22ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 2;
    jPanel11.add(jButton22, gridBagConstraints);

    jTabbedPane1.addTab("connectToMainServer", jPanel11);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jTabbedPane1)
            .addGap(0, 0, 0))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, Short.MAX_VALUE)
            .addGap(0, 0, 0))
    );

    jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, 0)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(0, 0, 0))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptActionPerformed
        if (!jToggleButton1.isSelected()) {
            this.setSize(dimension);
        }
        try {
            Formatter formatter = new Formatter("config.ini");
            formatter.format("IsFullScreen=" + " ");
            if (jToggleButton1.isSelected()) {
                formatter.format("true" + "\n");
            } else {
                formatter.format("false" + "\n");
            }
            formatter.format("ScreenExpansion=" + " " + dimension.width + " " + dimension.height + " " + jComboBox1.getSelectedIndex() + "\n");
            formatter.close();
        } catch(Exception e) {
            System.out.println(e);
        }
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_acceptActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected()) {
            gfxDev.setFullScreenWindow(this);
            jComboBox1.setEnabled(false);
        } else {
            gfxDev.setFullScreenWindow(null);
            this.setSize(dimension);
            jComboBox1.setEnabled(true);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            jTextField2.setEnabled(true);
        } else {
            jTextField2.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
       if (jCheckBox2.isSelected()) {
           jTextField2.setEnabled(false);
           jTextField1.setEnabled(false);
           jCheckBox1.setEnabled(false);
           jLabel1.setEnabled(false);
       } else {
           jTextField2.setEnabled(true);
           jTextField1.setEnabled(true);
           jCheckBox1.setEnabled(true);
           jLabel1.setEnabled(true);
       }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        switch (jComboBox1.getSelectedIndex()) {
            case (0):
            dimension.height = 500;
            dimension.width = 500;
            break;
            case (1):
            dimension.height = 480;
            dimension.width = 640;
            break;
            case (2):
            dimension.height = 768;
            dimension.width = 1024;
            break;
            case (3):
            dimension.height = 720;
            dimension.width = 1280;
            break;
            case (4):
            dimension.height = 1024;
            dimension.width = 1280;
            break;
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jTabbedPane1.setSelectedIndex(accountPage);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        jTabbedPane1.setSelectedIndex(6);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if (Arrays.equals(jPasswordField1.getPassword(), jPasswordField2.getPassword())) {
            jLabel4.setForeground(Color.black);
            try {
                DatabaseProcedures databaseProcedures = new DatabaseProcedures(ipBDServer);
                if (databaseProcedures.registDB(jTextField6.getText(), String.valueOf(jPasswordField1.getPassword()))) {
                    online = true;
                    jButton1.setEnabled(true);
                    accountPage = 8;
                    name = jTextField6.getText();
                    jLabel11.setText(name);
                     jTabbedPane1.setSelectedIndex(0);
                    } else {
                        jLabel4.setForeground(Color.red);
                    }
                    databaseProcedures.close();
            } catch (SQLException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabel6.setForeground(Color.RED);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        try {
            int index = jList1.getSelectedIndex();
            listModel.remove(index);
            serversName.remove(index);
            serversIp.remove(index);
            serversPass.remove(index);
            Formatter formatter = new Formatter("servers.txt");
            int size = serversName.size();
            for (int i = 0; i < size; i++) {
               if (size != i + 1) { 
                   formatter.format("%s %s %s\n", serversName.get(i), serversIp.get(i), serversPass.get(i));
               } else {
                   formatter.format("%s %s %s", serversName.get(i), serversIp.get(i), serversPass.get(i));
               }
            }
            formatter.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        if (!jTextField7.getText().equals("") && !jTextField3.getText().equals("")) {
            try {
                FileWriter writer = new FileWriter("servers.txt", true);
                BufferedWriter bufferWriter = new BufferedWriter(writer);
                bufferWriter.write("\n" + jTextField7.getText() + " " + jTextField3.getText() + " " + "\"" + String.valueOf(jPasswordField3.getPassword()) + "\"");
                bufferWriter.close();
            }
            catch (Exception e) {
                System.out.println(e);
            }
            listModel.addElement(jTextField7.getText());
            serversName.add(jTextField7.getText());
            serversIp.add(jTextField3.getText());
            serversPass.add("\"" + String.valueOf(jPasswordField3.getPassword()) + "\"");
            jTabbedPane1.setSelectedIndex(4);
            jLabel8.setForeground(Color.black);
            jLabel7.setForeground(Color.black);
        } else {
            jLabel8.setForeground(Color.red);
            jLabel7.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if (jCheckBox3.isSelected()) {
            online = true;
            jButton11.setEnabled(true);
        } else {
            online = false;
            jButton11.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
            DatabaseProcedures databaseProcedures = new DatabaseProcedures(ipBDServer);
            if (databaseProcedures.loginDB(jTextField4.getText(), jTextField5.getText())) {
                online = true;
                jButton1.setEnabled(true);
                jLabel10.setVisible(false);
                accountPage = 8;
                name = jTextField4.getText();
                jLabel11.setText(name);
                jTabbedPane1.setSelectedIndex(0);
            } else {
                jLabel10.setVisible(true);
            }
            databaseProcedures.close();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        accountPage = 5;
        jTabbedPane1.setSelectedIndex(accountPage);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        ipBDServer = jTextField8.getText();
        accountPage = 5;
        jTabbedPane1.setSelectedIndex(accountPage);
    }//GEN-LAST:event_jButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept;
    private javax.swing.JButton cancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.DefaultListModel listModel;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
